### ISSUE TITLE
Multi-gpu training issue: device cuda mismatch

### ISSUE THREAD

**Issue by mengyuest** [IBM/bLVNet-TAM#2]
Hi, in training I encountered `RuntimeError: Function SqueezeBackward1 returned an invalid gradient at index 0 - expected device cuda:3 but got cuda:4`. In the paper I remember you used 8 GPUs. Have you encountered this issue before? Thanks.

The command I am using is `python3 train.py --datadir ../../sthsthv2 --dataset st2stv2 -d 101 --groups 16 --logdir ./logs --lr 0.01 -b 64 --dropout 0.5 -j 36 --blending_frames 3 --epochs 50 --disable_scaleup --imagenet_blnet_pretrained`. And I have the pretrained model ready under `./pretrained`.

The environment I am using under Ubuntu18.04.3 LTS is:
```
#Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
ca-certificates           2019.11.27                    0
certifi                   2019.11.28               py37_0
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
ncurses                   6.1                  he6710b0_1
numpy                     1.17.4                   pypi_0    pypi
openssl                   1.1.1d               h7b6447c_3
pillow                    6.2.1                    pypi_0    pypi
pip                       19.3.1                   py37_0
protobuf                  3.11.1                   pypi_0    pypi
python                    3.7.5                h0371630_0
readline                  7.0                  h7b6447c_5
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.3.3                    pypi_0    pypi
setuptools                42.0.2                   py37_0
six                       1.13.0                   pypi_0    pypi
sqlite                    3.30.1               h7b6447c_0
tensorboard-logger        0.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0
torch                     1.3.1                    pypi_0    pypi
torchvision               0.4.2                    pypi_0    pypi
tqdm                      4.40.2                   pypi_0    pypi
wheel                     0.33.6                   py37_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
```

**Comment by chunfuchen** [comment]
should be resolved by fadab3b4. do you mind trying it again? thanks

**Comment by mengyuest** [comment]
Thanks for your reply. I tried the latest code but still encountered the same issue. I also tried different pytorch version (1.3.1, 1.2.0, 1.1.0) and different servers and the problem persists. Have you encountered this problem from your side?

**Comment by mengyuest** [comment]
Sorry I found out it was my fault (the updated version not sync to the remote servers...) Now the updated version works. Thanks for your help~
